### ISSUE TITLE
Add support for defining environment variables in launch configuration

### ISSUE THREAD

**Issue by nirvdrum** [graalvm/vscode-extensions#19]
It's fairly common when running or debugging an application to want to specify environment variables. Other launchers I've used support the `env` property, accepting a map of key:value pairs. It would be really nice if this were configurable for the GraalVM launcher as well. My use case is running and debugging code on TruffleRuby.

**Comment by entlicher** [comment]
This is fixed by https://github.com/graalvm/vscode-extensions/commit/e1d627805538926b42971efc002809418a6e2964
`env` property can be specified, it's value is an object of `"key" : "value"` pairs. To delete a property, use `"key" : null`
A new version of GraalVM extension 0.5.25 was released today, which contains this fix.
